### ISSUE TITLE
Problem With Generated OTPs

### ISSUE THREAD

**Issue by antoine-ki** [codewise/ios-otp-generators#1]
Hi,
I am trying to use your TOTP generator. The generated tokens are different than the real ones.
I tried setting the secret key to be the same as my gmail account one and i get different OTPs.
Checked the syncronization, doesnt seem to be the problem.
Can you shed light on the issue?

To recap:
1- gave my google secret as a string (32 digits)
2- generating OTPs

OTPs are not correct.

My code is the following:

Code extract:

    var generatorTimer: NSTimer?
    var labelTimer: NSTimer?
    var generator: TOTPGenerator!
    var timeCounter = 0
    
    func refreshTokenLabel() {

            print((self.generator).generateOTP())
        
    }
    
    func refreshTimerLabel() {
        if self.timeCounter == 0 {
            self.refreshTokenLabel()
            self.timeCounter = Int((self.generator).period)
            print(NSLocalizedString("Next in... ", comment: "") + "\(self.timeCounter)s")
        } else {
            self.timeCounter--
            print(NSLocalizedString("Next in... ", comment: "") + "\(self.timeCounter)s")
        }
    }

     override func viewDidLoad() {

        
        generator = TOTPGenerator(secret: "(32digits)", period: 30)!
        generatorTimer = NSTimer.scheduledTimerWithTimeInterval((generator).period, target: self, selector: "refreshTokenLabel", userInfo: nil, repeats: true)
        labelTimer = NSTimer.scheduledTimerWithTimeInterval(1, target: self, selector: "refreshTimerLabel", userInfo: nil, repeats: true)
        
        
        //refreshTokenLabel()
        self.refreshTimerLabel()

}

**Comment by marcin-zbijowski** [comment]
Hi, 

Thanks for contact and the code extract. I'll try to look at it as soon as I can.

**Comment by antoine-ki** [comment]
Great. thanks,

it might be a timer issue. I noticed that whenever i restart the code the timer restarts from 30 regardless of the actual value that it should be taking.

**Comment by antoine-ki** [comment]
Hi again,

Did you get a chance to look at your code?

I would really appreciate it if you take 10 mins to review it and fix the issue.

Thanks :dancers:

**Comment by marcin-zbijowski** [comment]
What do you compare it with exactly?

**Comment by antoine-ki** [comment]
Google Authenticator's OTPs.
Online TOTP generators.
SMS OTP generated by Facebook.

Basically everything.

**Comment by antoine-ki** [comment]
Hi,
are you planning to fix it or should i look for another module?

If i can assist you in any way please do let me know

**Comment by marcin-zbijowski** [comment]
Fixed in 2fa3e5a06628f2affab7faab4defca57dfa3e47e
There was no Base32 encoding. I added it to the project and verified with Google Authenticator and [OATH Toolkit](http://www.nongnu.org/oath-toolkit/)

**Comment by antoine-ki** [comment]
Works! Thank you Marcin.
