### ISSUE TITLE
Not able to run and check demo.

### ISSUE THREAD

**Issue by cjd1307** [codewise/ios-otp-generators#3]
Hello,

I just downloaded the sample. I am using Xcode Version 7.2. I tried running the application. It was built successfully but clicking on any option from Counter Based or Time Base its crashing with below error.

**string contains some invalid characters.
fatal error: unexpectedly found nil while unwrapping an Optional value**

Its crashing in "generatorWithSecretKey" function in "GeneratorFactory.swift"

**Comment by marcin-zbijowski** [comment]
There was an error in example app, but fixed with last commit
